# IndexError is thrown when trying to access an item at an invalid index
l1 = [1, 2, 3]
l1[3]

# IndexError: list index out of range