# ValueError is thrown when a function's argument is of an inappropriate type
int('xyz')

# ValueError: invalid literal for int() with base 10: 'xyz